export const products = [
  {
    id: 1,
    name: "Premium Wireless Headphones",
    category: {
      name: "Electronics",
      image: "/images/laptop-stand.jpg",
      count: "500+ Products",
      description: "Latest tech and gadgets",
    },
    price: 299,
    rating: 4.5,
    reviews: 128,
    image: "/images/headphones.jpg",
    images: [
      "/images/headphones.jpg",
      "/images/headphones-side.jpg",
      "/images/headphones-case.jpg",
    ],
    description:
      "Experience superior sound quality with our premium wireless headphones. Featuring advanced noise cancellation technology, these headphones deliver crystal-clear audio whether you're listening to music, taking calls, or enjoying your favorite podcasts.",
    features: [
      "Active Noise Cancellation",
      "40-hour battery life",
      "Premium leather ear cushions",
      "Bluetooth 5.0 connectivity",
      "Built-in microphone",
      "Foldable design with carrying case",
    ],
    specifications: {
      Brand: "LuxeAudio",
      Model: "LA-WH1000",
      Color: "Midnight Black",
      Weight: "250g",
      Connectivity: "Bluetooth 5.0, 3.5mm jack",
      Battery: "40 hours playback",
    },
    inStock: true,
  },
  {
    id: 2,
    name: "Smart Watch Pro",
    category: {
      name: "Electronics",
      image: "/images/laptop-stand.jpg",
      count: "500+ Products",
      description: "Latest tech and gadgets",
    },
    price: 399,
    rating: 4.8,
    reviews: 256,
    image: "/images/smartwatch.jpg",
    images: [
      "/images/smartwatch.jpg",
      "/images/smartwatch-side.jpg",
      "/images/smartwatch-apps.jpg",
    ],
    description:
      "Advanced fitness tracking and smart notifications in a sleek design. Monitor your health, stay connected, and achieve your fitness goals.",
    features: [
      "Heart rate monitoring",
      "GPS tracking",
      "Water resistant",
      "7-day battery life",
      "Sleep tracking",
      "Multiple sport modes",
    ],
    specifications: {
      Brand: "TechFit",
      Model: "TF-SW500",
      Color: "Space Gray",
      Weight: "45g",
      Display: "1.4 inch AMOLED",
      Battery: "7 days",
    },
    inStock: true,
  },
  {
    id: 3,
    name: "Designer Leather Jacket",
    category: {
      name: "Fashion",
      image: "/images/laptop-stand.jpg",
      count: "800+ Products",
      description: "Trendy apparel and accessories",
    },
    price: 499,
    rating: 4.6,
    reviews: 89,
    image: "/images/leather-jacket.jpg",
    images: [
      "/images/leather-jacket.jpg",
      "/images/leather-jacket-back.jpg",
      "/images/leather-jacket-detail.jpg",
    ],
    description:
      "Premium leather jacket with modern design. Crafted from genuine leather with attention to detail and comfort.",
    features: [
      "Genuine leather",
      "Multiple pockets",
      "Soft inner lining",
      "YKK zippers",
      "Adjustable cuffs",
      "Classic fit",
    ],
    specifications: {
      Brand: "UrbanStyle",
      Material: "Genuine Leather",
      Color: "Black",
      Sizes: "S, M, L, XL",
      Care: "Professional leather cleaning",
      Origin: "Italy",
    },
    inStock: true,
  },
  {
    id: 4,
    name: "Running Shoes Elite",
    category: {
      name: "Sports & Fitness",
      image: "/images/laptop-stand.jpg",
      count: "200+ Products",
      description: "Gear for active lifestyle",
    },
    price: 159,
    rating: 4.7,
    reviews: 342,
    image: "/images/running-shoes.jpg",
    images: [
      "/images/running-shoes.jpg",
      "/images/running-shoes-side.jpg",
      "/images/running-shoes-sole.jpg",
    ],
    description:
      "Professional running shoes designed for athletes. Lightweight, breathable, and built for performance.",
    features: [
      "Breathable mesh upper",
      "Responsive cushioning",
      "Durable rubber outsole",
      "Lightweight design",
      "Arch support",
      "Reflective details",
    ],
    specifications: {
      Brand: "RunPro",
      Model: "RP-Elite",
      Color: "Blue/White",
      Weight: "280g",
      Sizes: "7-13 US",
      Type: "Road running",
    },
    inStock: true,
  },
  {
    id: 5,
    name: "Modern Table Lamp",
    category: {
      name: "Home & Living",
      image: "/images/laptop-stand.jpg",
      count: "350+ Products",
      description: "Beautiful home essentials",
    },
    price: 89,
    rating: 4.4,
    reviews: 67,
    image: "/images/table-lamp.jpg",
    images: [
      "/images/table-lamp.jpg",
      "/images/table-lamp-on.jpg",
      "/images/table-lamp-detail.jpg",
    ],
    description:
      "Elegant table lamp with adjustable brightness. Perfect for reading, working, or ambient lighting.",
    features: [
      "Adjustable brightness",
      "Touch control",
      "LED technology",
      "Energy efficient",
      "Modern design",
      "Stable base",
    ],
    specifications: {
      Brand: "LightHome",
      Model: "LH-TL200",
      Color: "Matte Black",
      Height: "45cm",
      Power: "12W LED",
      Lifespan: "50,000 hours",
    },
    inStock: true,
  },
  {
    id: 6,
    name: "Laptop Stand Pro",
    category: {
      name: "Electronics",
      image: "/images/laptop-stand.jpg",
      count: "500+ Products",
      description: "Latest tech and gadgets",
    },
    price: 79,
    rating: 4.3,
    reviews: 145,
    image: "/images/laptop-stand.jpg",
    images: [
      "/images/laptop-stand.jpg",
      "/images/laptop-stand-angle.jpg",
      "/images/laptop-stand-use.jpg",
    ],
    description:
      "Ergonomic laptop stand for better posture. Adjustable height and angle for maximum comfort.",
    features: [
      "Adjustable height",
      "Aluminum construction",
      "Non-slip pads",
      "Cable management",
      "Portable design",
      "Supports up to 17 inch laptops",
    ],
    specifications: {
      Brand: "DeskPro",
      Model: "DP-LS100",
      Color: "Silver",
      Material: "Aluminum alloy",
      Weight: "1.2kg",
      Compatibility: "All laptops",
    },
    inStock: true,
  },
  {
    id: 7,
    name: "Casual T-Shirt",
    category: {
      name: "Fashion",
      image: "/images/laptop-stand.jpg",
      count: "800+ Products",
      description: "Trendy apparel and accessories",
    },
    price: 39,
    rating: 4.2,
    reviews: 234,
    image: "/images/tshirt.jpg",
    images: [
      "/images/tshirt.jpg",
      "/images/tshirt-back.jpg",
      "/images/tshirt-detail.jpg",
    ],
    description:
      "Comfortable cotton t-shirt in various colors. Perfect for everyday wear with a relaxed fit.",
    features: [
      "100% cotton",
      "Breathable fabric",
      "Pre-shrunk",
      "Reinforced seams",
      "Multiple colors",
      "Machine washable",
    ],
    specifications: {
      Brand: "ComfortWear",
      Material: "100% Cotton",
      Fit: "Regular",
      Sizes: "XS-XXL",
      Colors: "10 colors available",
      Care: "Machine wash cold",
    },
    inStock: true,
  },
  {
    id: 8,
    name: "Yoga Mat Premium",
    category: {
      name: "Sports & Fitness",
      image: "/images/laptop-stand.jpg",
      count: "200+ Products",
      description: "Gear for active lifestyle",
    },
    price: 49,
    rating: 4.6,
    reviews: 178,
    image: "/images/yoga-mat.jpg",
    images: [
      "/images/yoga-mat.jpg",
      "/images/yoga-mat-rolled.jpg",
      "/images/yoga-mat-texture.jpg",
    ],
    description:
      "Non-slip yoga mat with extra cushioning. Perfect for yoga, pilates, and floor exercises.",
    features: [
      "Non-slip surface",
      "Extra thick padding",
      "Eco-friendly material",
      "Easy to clean",
      "Carrying strap included",
      "Moisture resistant",
    ],
    specifications: {
      Brand: "YogaLife",
      Model: "YL-PM600",
      Color: "Purple",
      Thickness: "6mm",
      Size: "183cm x 61cm",
      Material: "TPE",
    },
    inStock: true,
  },
];

export const getProductById = (id: number) => {
  return products.find((p) => p.id === id);
};

export const categories = [
  {
    name: "All",
    image: "/images/laptop-stand.jpg",
    count: "500+ Products",
    description: "Everything you may want",
  },
  {
    name: "Electronics",
    image: "/images/laptop-stand.jpg",
    count: "500+ Products",
    description: "Latest tech and gadgets",
  },
  {
    name: "Fashion",
    image: "/images/laptop-stand.jpg",
    count: "800+ Products",
    description: "Trendy apparel and accessories",
  },
  {
    name: "Home & Living",
    image: "/images/laptop-stand.jpg",
    count: "350+ Products",
    description: "Beautiful home essentials",
  },
  {
    name: "Sports & Fitness",
    image: "/images/laptop-stand.jpg",
    count: "200+ Products",
    description: "Gear for active lifestyle",
  },
];
